In [2]:
import numpy as np
import pandas  as pd 
import matplotlib.pyplot as plt 
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.mixture import GaussianMixture
import joblib
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

# Data Collection and Initial Analytics

In [12]:
data_from_db = {
  "events": [
    {
      "_id": "67a3a99209bf1abd07d9309e",
      "title": "Cricket League Finals",
      "type": "Sports",
      "date": "2025-03-12",
      "time": "19:30",
      "venue": "MA Chidambaram Stadium",
      "description": "Watch top teams battle it out in the much-awaited cricket finals, featuring thrilling moments and nail-biting finishes.",
      "price": "1500",
      "city": "Chennai",
      "image": "https://img.freepik.com/free-photo/world-cup-cricket-player-background_1409-6235.jpg?ga=GA1.1.616475983.1738604229&semt=ais_incoming",
      "__v": 0
    },
    {
      "_id": "67a3aa2409bf1abd07d930aa",
      "title": "Robotics Workshop",
      "type": "Workshop",
      "date": "2025-02-12",
      "time": "11:42",
      "venue": "Anna University",
      "description": "Learn robotics from industry experts, build your own bot, and participate in hands-on projects.",
      "price": "200",
      "city": "Chennai",
      "image": "https://img.freepik.com/free-photo/young-man-woman-vr-glasses-doing-experiments-robotics-laboratory-robot-tools_1268-23324.jpg?ga=GA1.1.616475983.1738604229&semt=ais_incoming",
      "__v": 0
    },
    {
      "_id": "67a3aa5809bf1abd07d930ac",
      "title": "Food and Wine Festival",
      "type": "Culturals",
      "date": "2025-02-19",
      "time": "14:45",
      "venue": "Phoenix MarketCity",
      "description": "Experience a delightful evening with exotic cuisines, premium wines, and live music performances.",
      "price": "900",
      "city": "Chennai",
      "image": "https://img.freepik.com/premium-photo/world-food-day-celebration-images_1046319-69943.jpg?ga=GA1.1.616475983.1738604229&semt=ais_incoming",
      "__v": 0
    },
    {
      "_id": "67a3aa9209bf1abd07d930ae",
      "title": "Chess Championship\t",
      "type": "Sports",
      "date": "2025-02-25",
      "time": "11:00",
      "venue": "Jawaharlal Nehru Stadium",
      "description": "A prestigious chess tournament bringing together grandmasters and amateurs to compete in a strategic battle.",
      "price": "700",
      "city": "Chennai",
      "image": "https://img.freepik.com/premium-photo/large-modern-futuristic-looking-chess-board-with-chess-piece-about-topple_973275-88029.jpg?ga=GA1.1.616475983.1738604229&semt=ais_incoming",
      "__v": 0
    },
    {
      "_id": "67a3aac209bf1abd07d930b0",
      "title": "Startup Pitch Day",
      "type": "Workshop",
      "date": "2025-02-06",
      "time": "02:45",
      "venue": "T-Hub Chennai",
      "description": "A golden opportunity for budding entrepreneurs to present their ideas to investors and industry leaders.",
      "price": "1500",
      "city": "Chennai",
      "image": "https://img.freepik.com/free-photo/front-view-young-attractive-lady-blue-construction-suit-helmet-working-holding-heavy-metallic-thing-daytime-buildings-architecture-construction_140725-16241.jpg?ga=GA1.1.616475983.1738604229&semt=ais_incoming",
      "__v": 0
    },
    {
      "_id": "67a999cd8495d83d978a358c",
      "title": "ComicCon Banglore",
      "type": "Culturals",
      "date": "2025-02-12",
      "time": "09:00",
      "venue": "World Trade Center, Bangalore.",
      "description": "ComicCon is a popular fan convention that celebrates comic books and related pop culture entertainment. It's a place where fans of comics, movies, TV shows, video games, and more gather to meet creators, experts, and fellow enthusiasts",
      "price": "900",
      "city": "Bangalore",
      "image": "https://sm.ign.com/t/ign_in/screenshot/default/c-cropg-custom-v1730324044-anczhsdyhmtz79hzdcll_fmv1.2560.jpg",
      "__v": 0
    },
    {
      "_id": "67b4840af65b0c3880fd0f74",
      "title": "hip hop concert",
      "type": "Culturals",
      "date": "2025-02-26",
      "time": "20:27",
      "venue": "Chepauk Stadium Chennai",
      "description": "defe ewkmgm kgmr gkrmg kefem ekmf fekmf ekfme.",
      "price": "198",
      "city": "Delhi",
      "image": "https://img.freepik.com/free-photo/world-cup-cricket-player-background_1409-6235.jpg?ga=GA1.1.616475983.1738604229&semt=ais_incoming",
      "__v": 0
    },
    {
      "_id": "67c00f5c620f29c233ee70e7",
      "title": "Hip hop tamizha pro show",
      "type": "Culturals",
      "date": "2025-02-28",
      "time": "15:00",
      "venue": "KCG college of technology",
      "description": "duewhwd ue uh dis p33ojed dwiohjojd 32ieh323 eijwsb 2uhe e2iehehe 2ih1ee3.",
      "price": "500",
      "city": "Mumbai",
      "image": "",
      "__v": 0
    }
  ]
}

dataset = pd.DataFrame(
    data_from_db.get('events')
)
dataset.head()

,_id,title,type,date,time,venue,description,price,city,image,__v
0,67a3a99209bf1abd07d9309e,Cricket League Finals,Sports,2025-03-12,19:30,MA Chidambaram Stadium,Watch top teams battle it out in the much-awai...,1500,Chennai,https://img.freepik.com/free-photo/world-cup-c...,0
1,67a3aa2409bf1abd07d930aa,Robotics Workshop,Workshop,2025-02-12,11:42,Anna University,"Learn robotics from industry experts, build yo...",200,Chennai,https://img.freepik.com/free-photo/young-man-w...,0
2,67a3aa5809bf1abd07d930ac,Food and Wine Festival,Culturals,2025-02-19,14:45,Phoenix MarketCity,Experience a delightful evening with exotic cu...,900,Chennai,https://img.freepik.com/premium-photo/world-fo...,0
3,67a3aa9209bf1abd07d930ae,Chess Championship\t,Sports,2025-02-25,11:00,Jawaharlal Nehru Stadium,A prestigious chess tournament bringing togeth...,700,Chennai,https://img.freepik.com/premium-photo/large-mo...,0
4,67a3aac209bf1abd07d930b0,Startup Pitch Day,Workshop,2025-02-06,02:45,T-Hub Chennai,A golden opportunity for budding entrepreneurs...,1500,Chennai,https://img.freepik.com/free-photo/front-view-...,0

In [13]:
print("Shape of the dataset: ", dataset.shape)
dataset.info()

Shape of the dataset:  (8, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _id          8 non-null      object
 1   title        8 non-null      object
 2   type         8 non-null      object
 3   date         8 non-null      object
 4   time         8 non-null      object
 5   venue        8 non-null      object
 6   description  8 non-null      object
 7   price        8 non-null      object
 8   city         8 non-null      object
 9   image        8 non-null      object
 10  __v          8 non-null      int64
dtypes: int64(1), object(10)
memory usage: 832.0+ bytes

# Data Wrangling Process

In [14]:
dataset = dataset.iloc[:, 1:9]
dataset.head()

,title,type,date,time,venue,description,price,city
0,Cricket League Finals,Sports,2025-03-12,19:30,MA Chidambaram Stadium,Watch top teams battle it out in the much-awai...,1500,Chennai
1,Robotics Workshop,Workshop,2025-02-12,11:42,Anna University,"Learn robotics from industry experts, build yo...",200,Chennai
2,Food and Wine Festival,Culturals,2025-02-19,14:45,Phoenix MarketCity,Experience a delightful evening with exotic cu...,900,Chennai
3,Chess Championship\t,Sports,2025-02-25,11:00,Jawaharlal Nehru Stadium,A prestigious chess tournament bringing togeth...,700,Chennai
4,Startup Pitch Day,Workshop,2025-02-06,02:45,T-Hub Chennai,A golden opportunity for budding entrepreneurs...,1500,Chennai

In [15]:
# Convert date and time to datetime format
dataset['datetime'] = pd.to_datetime(dataset['date'] + ' ' + dataset['time'])
dataset['day_of_week'] = dataset['datetime'].dt.dayofweek

In [17]:
dataset.head()

,title,type,date,time,venue,description,price,city,datetime,day_of_week
0,Cricket League Finals,Sports,2025-03-12,19:30,MA Chidambaram Stadium,Watch top teams battle it out in the much-awai...,1500,Chennai,2025-03-12 19:30:00,2
1,Robotics Workshop,Workshop,2025-02-12,11:42,Anna University,"Learn robotics from industry experts, build yo...",200,Chennai,2025-02-12 11:42:00,2
2,Food and Wine Festival,Culturals,2025-02-19,14:45,Phoenix MarketCity,Experience a delightful evening with exotic cu...,900,Chennai,2025-02-19 14:45:00,2
3,Chess Championship\t,Sports,2025-02-25,11:00,Jawaharlal Nehru Stadium,A prestigious chess tournament bringing togeth...,700,Chennai,2025-02-25 11:00:00,1
4,Startup Pitch Day,Workshop,2025-02-06,02:45,T-Hub Chennai,A golden opportunity for budding entrepreneurs...,1500,Chennai,2025-02-06 02:45:00,3

In [18]:
dataset.drop(columns=['date', 'time', 'venue', 'description', 'datetime'], inplace=True)

In [19]:
# Encode categorical data
label_enc = LabelEncoder()
dataset['type_encoded'] = label_enc.fit_transform(dataset['type'])
scaler = StandardScaler()
dataset[['price', 'day_of_week']] = scaler.fit_transform(dataset[['price', 'day_of_week']])

In [20]:
# Feature set for clustering
features = dataset[['price', 'day_of_week', 'type_encoded']]

In [21]:
# KMeans Clustering
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
dataset['KMeans_Cluster'] = kmeans.fit_predict(features)

# DBSCAN Clustering
dbscan = DBSCAN(eps=1.5, min_samples=2)
dataset['DBSCAN_Cluster'] = dbscan.fit_predict(features)

# Gaussian Mixture Model Clustering
gmm = GaussianMixture(n_components=3, random_state=42)
dataset['GMM_Cluster'] = gmm.fit_predict(features)

In [22]:
dataset.head()

,title,type,price,city,day_of_week,type_encoded,KMeans_Cluster,DBSCAN_Cluster,GMM_Cluster
0,Cricket League Finals,Sports,1.467154,Chennai,-0.301511,1,1,-1,1
1,Robotics Workshop,Workshop,-1.256588,Chennai,-0.301511,2,0,-1,0
2,Food and Wine Festival,Culturals,0.210042,Chennai,-0.301511,0,0,0,2
3,Chess Championship\t,Sports,-0.208995,Chennai,-1.507557,1,0,-1,2
4,Startup Pitch Day,Workshop,1.467154,Chennai,0.904534,2,1,-1,1

In [60]:
# Save models as .pkl files
with open('./trained_models/kmeans_model.joblib', 'wb') as f:
    joblib.dump(kmeans, f)

with open('./trained_models/dbscan_model.joblib', 'wb') as f:
    joblib.dump(dbscan, f)

with open('./trained_models/gmm_model.joblib', 'wb') as f:
    joblib.dump(gmm, f)

with open('./trained_models/scaler.joblib', 'wb') as f:
    joblib.dump(scaler, f)

with open('./trained_models/label_encoder.joblib', 'wb') as f:
    joblib.dump(label_enc, f)

In [29]:
dataset.to_csv('modified_datasets/events.csv')

In [61]:
data ={
    "title": "Tech Expo 2025",
    "type": "Workshop",
    "price": 1200,
    "city": "Chennai",
    "day_of_week": 3
}

In [63]:
# Convert JSON to DataFrame
data = pd.DataFrame([data])
print(data)

# Extract and preprocess input features
price = float(data.loc[0, 'price'])  # Accessing the first row
day_of_week = int(data.loc[0, 'day_of_week'])
event_type = data.loc[0, 'type']

            title      type  price     city  day_of_week
0  Tech Expo 2025  Workshop   1200  Chennai            3

In [64]:
# Encode event type
type_encoded = label_enc.transform([[event_type]])[0]  # Ensure it's a list before transforming

c:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [65]:
print(type_encoded)

2

In [66]:
# Convert features to a DataFrame and scale
features = pd.DataFrame([[price, day_of_week]], columns=['price', 'day_of_week'])
print(features)

    price  day_of_week
0  1200.0            3

In [67]:
features_scaled = scaler.transform(features)  # Transform correctly
print(features_scaled)

[[0.83859847 0.90453403]]

In [68]:
# Convert scaled features back into a DataFrame with correct column names
features_scaled_df = pd.DataFrame(features_scaled, columns=['price', 'day_of_week'])

# Add type_encoded back to the scaled DataFrame
features_scaled_df["type_encoded"] = type_encoded

In [69]:
print(features_scaled_df)

      price  day_of_week  type_encoded
0  0.838598     0.904534             2

In [70]:
 # Get predictions
kmeans_cluster = int(kmeans.predict(features_scaled_df)[0])
gmm_cluster = int(gmm.predict(features_scaled_df)[0])

# Handle DBSCAN prediction
dbscan_cluster = -1  # Default to noise

In [71]:
dbscan_cluster = int(dbscan.fit_predict(features_scaled_df)[0])

In [72]:
print(dbscan_cluster)

-1

In [73]:
# Get recommended events, ignoring DBSCAN cluster if it's -1
recommended_events = dataset[
    (dataset["KMeans_Cluster"] == kmeans_cluster) |
    (dataset["GMM_Cluster"] == gmm_cluster) |
    ((dataset["DBSCAN_Cluster"] == dbscan_cluster) & (dbscan_cluster != -1))
    ][["title", "type", "city"]].to_dict(orient="records")

In [74]:
print(recommended_events)

[{'title': 'Cricket League Finals', 'type': 'Sports', 'city': 'Chennai'}, {'title': 'Startup Pitch Day', 'type': 'Workshop', 'city': 'Chennai'}]